apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mosquitto
  namespace: devices
spec:
  serviceName: "mqqt-service"        
  replicas: 1
  selector:
    matchLabels:
      name: mosquitto
  template:
    metadata:
      labels:
        name: mosquitto
    spec:
      hostNetwork: true
      containers:
      - name: mosquitto
        image: 192.168.31.115:5000/arm/eclipse-mosquitto
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-configmap
      nodeSelector:
        cpu: arm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-configmap
  namespace: devices
data:
  mosquitto.conf: |-
    listener 1883 0.0.0.0
    allow_anonymous true
    log_dest stdout

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mosquitto-service
#   namespace: devices
# spec:
#   type: LoadBalancer
#   selector:
#     name: mosquitto
#   ports:
#     - name: mosquitto
#       protocol: TCP
#       port: 1883
#       targetPort: 1883
