apiVersion: v1
kind: ConfigMap
metadata:
  name: driver-config
data:
  deviceshifu_config.yaml: |
    deviceShifu:
      name: "wheeltec_robot"
      type: "ros2"
      properties:
        ros2:
          namespace: "/wheeltec_robot"
          topics:
            - name: "cmd_vel"
              type: "geometry_msgs/Twist"
            - name: "camera/image"
              type: "sensor_msgs/Image"
---
apiVersion: v1
kind: Secret
metadata:
  name: mqtt-secret
type: Opaque
data:
  mqtt-username: d2hlZWx0ZWM=  # wheeltec
  mqtt-password: ZG9uZ2d1YW4=  # dongguan
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-node
  template:
    metadata:
      labels:
        app: driver-node
    spec:
      containers:
      - name: driver-node
        image: driver-node:1.0
        imagePullPolicy: Never
        env:
        - name: ROS_DOMAIN_ID
          value: "0"
        - name: MQTT_BROKER
          value: "mosquitto"
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mqtt-secret
              key: mqtt-username
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mqtt-secret
              key: mqtt-password
        - name: DEVICE_ID
          value: "device001"
        volumeMounts:
        - name: config
          mountPath: /ros_ws/install/driver_node_ros2/share/driver_node_ros2/config
      volumes:
      - name: config
        configMap:
          name: driver-config
---
apiVersion: v1
kind: Service
metadata:
  name: driver-node-service
spec:
  selector:
    app: driver-node
  ports:
  - port: 1883
    targetPort: 1883
    name: mqtt
  type: ClusterIP