apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-node
spec:
  template:
    spec:
      containers:
      - name: driver-node
        image: 192.168.31.115:5000/arm/nesc/driver-node:1.0
        imagePullPolicy: IfNotPresent  # 推荐策略
        command: ["/bin/bash", "-c"]
        args: ["source /opt/ros/foxy/setup.bash && ros2 run driver_node_ros2 driver_node.py"]
        env:
        - name: ROS_DOMAIN_ID
          value: "0"
        - name: MQTT_BROKER
          value: "mosquitto"
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mqtt-secret
              key: mqtt-username
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mqtt-secret
              key: mqtt-password
        - name: DEVICE_ID
          value: "device001"
        livenessProbe:
          exec:
            command:
            - ros2
            - node
            - info
            - /deviceshifu_driver
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - ros2
            - topic
            - list
          initialDelaySeconds: 15
          timeoutSeconds: 5