apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-ros1
  labels:
    app: driver-ros1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-ros1
  template:
    metadata:
      labels:
        app: driver-ros1
    spec:
      containers:
      - name: driver-ros1
        image: driver_ros1:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080