apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-ros2
  labels:
    app: driver-ros2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-ros2
  template:
    metadata:
      labels:
        app: driver-ros2
    spec:
      containers:
      - name: driver-ros2
        image: driver_ros2:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080