apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devices

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- network-policy.yaml

commonLabels:
  app.kubernetes.io/name: ros-robot
  app.kubernetes.io/part-of: ros-robot 